CREATE TYPE UUID_TABLES AS ENUM ('WAVES', 'CARDS', 'BATTLE_CARDS', 'CHARACTER_MODES', 'STRATAGEM_CARDS');

CREATE VIEW global_uuids AS
SELECT id, 'WAVES'::UUID_TABLES AS in_table FROM waves
  UNION
SELECT id, 'CARDS'::UUID_TABLES AS in_table FROM cards
  UNION
SELECT id, 'BATTLE_CARDS'::UUID_TABLES AS in_table FROM battle_cards
  UNION
SELECT id, 'CHARACTER_MODES'::UUID_TABLES AS in_table FROM character_modes
  UNION
SELECT id, 'STRATAGEM_CARDS'::UUID_TABLES AS in_table FROM stratagem_cards;
