CREATE TABLE waves (
  id SERIAL PRIMARY KEY,
  external_id UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
  tcg_id VARCHAR UNIQUE NOT NULL,
  name VARCHAR UNIQUE NOT NULL,
  released DATE NOT NULL
);
